### ISSUE TITLE
register.php 

### ISSUE THREAD

**Issue by rodccosta** [h4kboot/plataformactfh4k#5]
missing includes 
include_once 'includes/register.inc.php';
include_once 'includes/functions.php';

**Comment by john-goes** [comment]
@h4kboot ajuda nois! hehe
Nem eu trocando pelo <strong>Conexao.php</strong> da `class` tá dando certo...

**Comment by h4kboot** [comment]
Eita essa plataforma ta desatualizada a séculos, mals vai usar time no rolê
ou cadastro único?

**Comment by john-goes** [comment]
Entao, na real queria só registrar mesmo sem inputar os dados manualmente no banco

**Comment by h4kboot** [comment]
Ve se isso ajuda!

**Comment by john-goes** [comment]
O que ajuda?
